### ISSUE TITLE
Game closes

### ISSUE THREAD

**Issue by hexdecimal16** [HackerPolice/MissedIT-Stable#5]
The game closes immediately after injecting. I am on the latest update 4, June 2020m

**Comment by tutoraddicts** [comment]
Need to update pointers

**Comment by hexdecimal16** [comment]
https://pastebin.com/wfaJn4mQ
Hope this helps

**Comment by PedroVictorCoding** [comment]
Where are you replacing that? @hexdecimal16

**Comment by hexdecimal16** [comment]
i don't know these are just the dumps

**Comment by tutoraddicts** [comment]
It's updated working
